# Generated by Django 2.2.5 on 2020-02-28 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_booking_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='seats',
            new_name='ticket',
        ),
    ]
